In [2]:
msg ="hi there!"
msg


'hi there!'

In [4]:
print("asd")

asd


In [31]:
#numpy arrays
import numpy as np
import matplotlib.pylab as plt
from numpy import random

list_one=[1,2,3,4,5,6]
np_arr_one = np.array(list_one, dtype=np.int8)
np_arr_one

m_list=[[1,2,3,4],[4,5,6,7,8],[2,5,7,8]]
np_m_arr=np.array(m_list, dtype=object)
np_m_arr

gen_arr = np.arange(1,10,2)#generated ints with step 2, so every second value is returned
gen_arr
floar_arr = np.linspace(1,10,8) #generated 10 values with 8digits after comma
floar_arr
zer_arr=np.zeros(5)
zer_arr
np.random.randint(1,6,3)#from 1 to 6 genereated 3 rand integers
np_m_arr_1=np.random.randint(1,6, size=(2,3)) #sets 2 arra with lentgh 3

#np.random.randint? #shows the documentaion of a method


In [45]:
#slicing and indexes
np_m_arr_1[0,0]=1
print(np_m_arr_1)
np_m_arr_1.itemset((0,1),2)
print("new array" ,np_m_arr_1)
np_m_arr_1.shape
print(np.take(np_m_arr_1,[1,4]))#1and 4 are indices which it turnes like into one array
np.put(np_m_arr_1,[1,4],[6,6])#put 6 nunmber values to inex position of 1 and 4
np_m_arr_1

[[1 6 5]
 [5 6 5]]
new array [[1 2 5]
 [5 6 5]]
[2 6]


array([[1, 6, 5],
       [5, 6, 5]])